/* AUTH */
export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAIL = 'GET_PATIENTS_FAIL';

export const CREATE_PATIENTS ='CREATE_PATIENTS';
export const CREATE_PATIENTS_SUCCESS = 'CREATE_PATIENTS_SUCCESS';
export const CREATE_PATIENTS_FAIL = 'CREATE_PATIENTS_FAIL';

export const DELETE_PATIENTS = 'DELETE_PATIENTS';
export const DELETE_PATIENTS_SUCCESS = 'DELETE_PATIENTS_SUCCESS';
export const DELETE_PATIENTS_FAIL = 'DELETE_PATIENTS_FAIL';
