export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAIL = 'GET_PATIENTS_FAIL';

export const GET_PATIENT_DETAIL = 'GET_PATIENT_DETAIL';
export const GET_PATIENT_DETAIL_SUCCESS = 'GET_PATIENT_DETAIL_SUCCESS';
export const GET_PATIENT_DETAIL_FAIL = 'GET_PATIENT_DETAIL_FAIL';
export const CLEAR_PATIENT_DETAIL = 'CLEAR_PATIENT_DETAIL';

export const CREATE_PATIENTS = 'CREATE_PATIENTS';
export const CREATE_PATIENTS_SUCCESS = 'CREATE_PATIENTS_SUCCESS';
export const CREATE_PATIENTS_FAIL = 'CREATE_PATIENTS_FAIL';

export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const UPDATE_PATIENT_FAIL = 'UPDATE_PATIENT_FAIL';

export const DELETE_PATIENTS = 'DELETE_PATIENTS';
export const DELETE_PATIENTS_SUCCESS = 'DELETE_PATIENTS_SUCCESS';
export const DELETE_PATIENTS_FAIL = 'DELETE_PATIENTS_FAIL';
