export const GET_MONTHLY_REVENUE = 'GET_MONTHLY_REVENUE';
export const GET_MONTHLY_REVENUE_SUCCESS = 'GET_MONTHLY_REVENUE_SUCCESS';
export const GET_MONTHLY_REVENUE_FAIL = 'GET_MONTHLY_REVENUE_FAIL';

export const GET_REVENUE_IN_RANGE = 'GET_REVENUE_IN_RANGE';
export const GET_REVENUE_IN_RANGE_SUCCESS = 'GET_REVENUE_IN_RANGE_SUCCESS';
export const GET_REVENUE_IN_RANGE_FAIL = 'GET_REVENUE_IN_RANGE_FAIL';

export const GET_GENERAL_STATISTIC = 'GET_GENERAL_STATISTIC';
export const GET_GENERAL_STATISTIC_SUCCESS = 'GET_GENERAL_STATISTIC_SUCCESS';
export const GET_GENERAL_STATISTIC_FAIL = 'GET_GENERAL_STATISTIC_FAIL';

export const GET_MONTHLY_PATIENTS = 'GET_MONTHLY_PATIENTS';
export const GET_MONTHLY_PATIENTS_SUCCESS = 'GET_MONTHLY_PATIENTS_SUCCESS';
export const GET_MONTHLY_PATIENTS_FAIL = 'GET_MONTHLY_PATIENTS_FAIL';

export const GET_MONTHLY_MEDICAL = 'GET_MONTHLY_MEDICAL';
export const GET_MONTHLY_MEDICAL_SUCCESS = 'GET_MONTHLY_MEDICAL_SUCCESS';
export const GET_MONTHLY_MEDICAL_FAIL = 'GET_MONTHLY_MEDICAL_FAIL';

