export const GET_MONTHLY_REVENUE = 'GET_MONTHLY_REVENUE';
export const GET_MONTHLY_REVENUE_SUCCESS = 'GET_MONTHLY_REVENUE_SUCCESS';
export const GET_MONTHLY_REVENUE_FAIL = 'GET_MONTHLY_REVENUE_FAIL';
