export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAIL = 'GET_EMPLOYEES_FAIL';

export const GET_EMPLOYEE_DETAIL = 'GET_EMPLOYEE_DETAIL';
export const GET_EMPLOYEE_DETAIL_SUCCESS = 'GET_EMPLOYEE_DETAIL_SUCCESS';
export const GET_EMPLOYEE_DETAIL_FAIL = 'GET_EMPLOYEE_DETAIL_FAIL';
export const CLEAR_EMPLOYEE_DETAIL = 'CLEAR_EMPLOYEE_DETAIL';

export const CREATE_EMPLOYEES = 'CREATE_EMPLOYEES';
export const CREATE_EMPLOYEES_SUCCESS = 'CREATE_EMPLOYEES_SUCCESS';
export const CREATE_EMPLOYEES_FAIL = 'CREATE_EMPLOYEES_FAIL';

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL';

export const DELETE_EMPLOYEES = 'DELETE_EMPLOYEES';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_FAIL = 'DELETE_EMPLOYEES_FAIL';
