export const GET_MEDICINES = 'GET_MEDICINES';
export const GET_MEDICINES_SUCCESS = 'GET_MEDICINES_SUCCESS';
export const GET_MEDICINES_FAIL = 'GET_MEDICINES_FAIL';

export const GET_MEDICINE_DETAIL = 'GET_MEDICINE_DETAIL';
export const GET_MEDICINE_DETAIL_SUCCESS = 'GET_MEDICINE_DETAIL_SUCCESS';
export const GET_MEDICINE_DETAIL_FAIL = 'GET_MEDICINE_DETAIL_FAIL';
export const CLEAR_MEDICINE_DETAIL = 'CLEAR_MEDICINE_DETAIL';

export const CREATE_MEDICINES = 'CREATE_MEDICINES';
export const CREATE_MEDICINES_SUCCESS = 'CREATE_MEDICINES_SUCCESS';
export const CREATE_MEDICINES_FAIL = 'CREATE_MEDICINES_FAIL';

export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const UPDATE_MEDICINE_SUCCESS = 'UPDATE_MEDICINE_SUCCESS';
export const UPDATE_MEDICINE_FAIL = 'UPDATE_MEDICINE_FAIL';

export const DELETE_MEDICINES = 'DELETE_MEDICINES';
export const DELETE_MEDICINES_SUCCESS = 'DELETE_MEDICINES_SUCCESS';
export const DELETE_MEDICINES_FAIL = 'DELETE_MEDICINES_FAIL';
