export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAIL = 'CREATE_APPOINTMENT_FAIL';

export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAIL = 'GET_APPOINTMENT_FAIL';

export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENTS';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENTS_SUCCESS';
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENTS_FAIL';

export const GET_EXAMINATIONS = 'GET_EXAMINATIONS';
export const GET_EXAMINATIONS_SUCCESS = 'GET_EXAMINATIONS_SUCCESS';
export const GET_EXAMINATIONS_FAIL = 'GET_EXAMINATIONS_FAIL';

export const GET_EXAMINATION_DETAIL = 'GET_EXAMINATION_DETAIL';
export const GET_EXAMINATION_DETAIL_SUCCESS = 'GET_EXAMINATION_DETAIL_SUCCESS';
export const GET_EXAMINATION_DETAIL_FAIL = 'GET_EXAMINATION_DETAIL_FAIL';
export const CLEAR_EXAMINATION_DETAIL = 'CLEAR_EXAMINATION_DETAIL';

export const CREATE_EXAMINATION = 'CREATE_EXAMINATION';
export const CREATE_EXAMINATION_SUCCESS = 'CREATE_EXAMINATION_SUCCESS';
export const CREATE_EXAMINATION_FAIL = 'CREATE_EXAMINATION_FAIL';

export const UPDATE_EXAMINATION = 'UPDATE_EXAMINATION';
export const UPDATE_EXAMINATION_SUCCESS = 'UPDATE_EXAMINATION_SUCCESS';
export const UPDATE_EXAMINATION_FAIL = 'UPDATE_EXAMINATION_FAIL';
